import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "@phosphor-icons/web/regular";
import "@phosphor-icons/web/fill";
import "@phosphor-icons/web/bold";
import { UserProvider } from "@/lib/userContext";

import { GeolocationProvider } from "@/lib/GeolocationContext";
import { NearbyRestaurantsProvider } from "@/lib/nearbyRestuant";
import { ReservationTracker } from "@/lib/ReservationTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-center" />
        <GeolocationProvider>
          <UserProvider>
            <NearbyRestaurantsProvider>
              <ReservationTracker>
                {children}
              </ReservationTracker>  
            </NearbyRestaurantsProvider>
          </UserProvider>
        </GeolocationProvider>
      </body>
    </html>
  );
}
