import type { Metadata } from "next";
import { Geist, Geist_Mono, Hanken_Grotesk, Cormorant_Garamond, IBM_Plex_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "@phosphor-icons/web/regular";
import "@phosphor-icons/web/fill";
import "@phosphor-icons/web/bold";
import { UserProvider } from "@/lib/userContext";

import { GeolocationProvider } from "@/lib/GeolocationContext";
import { NearbyRestaurantsProvider } from "@/lib/nearbyRestuant";
import { ReservationTracker } from "@/lib/ReservationTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* The Bill of Fare typeface set: Hanken Grotesk carries the UI, Cormorant
   Garamond the menu headings, IBM Plex Mono the small uppercase labels.
   Self-hosted through next/font rather than the design's <link> to Google —
   next/font inlines the @font-face and preloads, so there is no render-blocking
   round trip to fonts.googleapis.com and no layout shift when it lands. */
const hanken = Hanken_Grotesk({
  variable: "--font-hanken",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["500", "600", "700"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${hanken.variable} ${cormorant.variable} ${plexMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-center" />
        <GeolocationProvider>
          <UserProvider>
            <NearbyRestaurantsProvider>
              <ReservationTracker>
                {children}
              </ReservationTracker>  
            </NearbyRestaurantsProvider>
          </UserProvider>
        </GeolocationProvider>
      </body>
    </html>
  );
}
